language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-less --save
#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "marsfun"
  - git config user.email "stin.fly@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - gh-pages
env:
 global:
   - GH_REF: github.com/marsfun/marsfun.github.io.git
